// Tile Block Sets Data - Different visual styles for game tiles
export interface TileBlock {
  id: string;
  name: string;
  description: string;
  price: number;
  preview: string; // emoji or icon
  colors: Record<number, { bg: string; text: string; glow: string }>;
}

// Generate all tile values from 2 to 2^100 (approximately 2.53e30)
const generateTileValues = (): number[] => {
  const values: number[] = [];
  for (let i = 1; i <= 100; i++) {
    values.push(Math.pow(2, i));
  }
  return values;
};

export const allTileValues = generateTileValues();

// Helper to generate diverse colors for a theme
const generateColorPalette = (baseColors: Array<{bg: string, text: string, glow: string}>) => {
  const colors: Record<number, { bg: string; text: string; glow: string }> = {};
  allTileValues.forEach((value, index) => {
    const colorIndex = index % baseColors.length;
    colors[value] = baseColors[colorIndex];
  });
  return colors;
};

export const availableTileBlocks: TileBlock[] = [
  {
    id: "neon-classic",
    name: "Neon Classic",
    description: "Original neon colors",
    price: 0,
    preview: "🌟",
    colors: generateColorPalette([
      { bg: "bg-[#00FFFF]", text: "text-[#0B0F19]", glow: "glow-cyan" },
      { bg: "bg-[#00FF99]", text: "text-[#0B0F19]", glow: "glow-lime" },
      { bg: "bg-[#FFD700]", text: "text-[#0B0F19]", glow: "glow-yellow" },
      { bg: "bg-[#FF6A00]", text: "text-white", glow: "glow-orange" },
      { bg: "bg-[#FF00FF]", text: "text-white", glow: "glow-magenta" },
      { bg: "bg-[#A100FF]", text: "text-white", glow: "glow-purple" },
      { bg: "bg-[#00CCFF]", text: "text-[#0B0F19]", glow: "glow-cyan" },
      { bg: "bg-[#66FF66]", text: "text-[#0B0F19]", glow: "glow-lime" },
      { bg: "bg-[#FFAA00]", text: "text-[#0B0F19]", glow: "glow-orange" },
      { bg: "bg-[#FF0099]", text: "text-white", glow: "glow-magenta" },
      { bg: "bg-gradient-to-br from-[#00FFFF] to-[#00FF99]", text: "text-[#0B0F19]", glow: "glow-cyan" },
      { bg: "bg-gradient-to-br from-[#FFD700] to-[#FF6A00]", text: "text-white", glow: "glow-yellow" },
      { bg: "bg-gradient-to-br from-[#FF00FF] to-[#A100FF]", text: "text-white", glow: "glow-magenta" },
      { bg: "bg-gradient-to-br from-[#00CCFF] to-[#A100FF]", text: "text-white", glow: "glow-purple" },
      { bg: "bg-gradient-to-br from-[#66FF66] to-[#FFD700]", text: "text-[#0B0F19]", glow: "glow-lime" },
      { bg: "bg-gradient-to-br from-[#FF6A00] to-[#FF00FF]", text: "text-white", glow: "glow-orange" },
      { bg: "bg-gradient-to-br from-[#A100FF] via-[#FF00FF] to-[#00FFFF]", text: "text-white", glow: "glow-intense-purple" },
      { bg: "bg-gradient-to-br from-[#FFD700] via-[#FF00FF] to-[#00FFFF]", text: "text-white", glow: "glow-intense-magenta" },
      { bg: "bg-gradient-to-br from-[#00FF99] via-[#00FFFF] to-[#A100FF]", text: "text-white", glow: "glow-intense-cyan" },
      { bg: "bg-gradient-to-br from-[#FF6A00] via-[#FFD700] to-[#00FF99]", text: "text-white", glow: "glow-intense-yellow" },
    ]),
  },
  {
    id: "fire-blaze",
    name: "Fire Blaze",
    description: "Burning hot flames",
    price: 500,
    preview: "🔥",
    colors: generateColorPalette([
      { bg: "bg-[#FF4500]", text: "text-white", glow: "glow-orange" },
      { bg: "bg-[#FF6347]", text: "text-white", glow: "glow-orange" },
      { bg: "bg-[#FF7F50]", text: "text-white", glow: "glow-orange" },
      { bg: "bg-[#FFA500]", text: "text-[#0B0F19]", glow: "glow-yellow" },
      { bg: "bg-[#FFD700]", text: "text-[#0B0F19]", glow: "glow-yellow" },
      { bg: "bg-[#FFFF00]", text: "text-[#0B0F19]", glow: "glow-yellow" },
      { bg: "bg-[#FF8C00]", text: "text-white", glow: "glow-orange" },
      { bg: "bg-[#FF2400]", text: "text-white", glow: "glow-orange" },
      { bg: "bg-[#FFB000]", text: "text-[#0B0F19]", glow: "glow-yellow" },
      { bg: "bg-[#FF5500]", text: "text-white", glow: "glow-orange" },
      { bg: "bg-gradient-to-br from-[#FF0000] to-[#FF6347]", text: "text-white", glow: "glow-orange" },
      { bg: "bg-gradient-to-br from-[#FF4500] to-[#FFD700]", text: "text-white", glow: "glow-yellow" },
      { bg: "bg-gradient-to-br from-[#FFD700] to-[#FFFF00]", text: "text-[#0B0F19]", glow: "glow-yellow" },
      { bg: "bg-gradient-to-br from-[#FF2400] to-[#FF8C00]", text: "text-white", glow: "glow-orange" },
      { bg: "bg-gradient-to-br from-[#FF7F50] to-[#FFB000]", text: "text-white", glow: "glow-orange" },
      { bg: "bg-gradient-to-br from-[#FF0000] via-[#FF6347] to-[#FFD700]", text: "text-white", glow: "glow-intense-orange" },
      { bg: "bg-gradient-to-br from-[#FF4500] via-[#FFD700] to-[#FFFF00]", text: "text-white", glow: "glow-intense-yellow" },
      { bg: "bg-gradient-to-br from-[#FF2400] via-[#FF7F50] to-[#FFB000]", text: "text-white", glow: "glow-intense-orange" },
    ]),
  },
  {
    id: "ice-frost",
    name: "Ice Frost",
    description: "Cool icy vibes",
    price: 500,
    preview: "❄️",
    colors: generateColorPalette([
      { bg: "bg-[#E0FFFF]", text: "text-[#0B0F19]", glow: "glow-cyan" },
      { bg: "bg-[#B0E0E6]", text: "text-[#0B0F19]", glow: "glow-cyan" },
      { bg: "bg-[#87CEEB]", text: "text-[#0B0F19]", glow: "glow-cyan" },
      { bg: "bg-[#4682B4]", text: "text-white", glow: "glow-cyan" },
      { bg: "bg-[#4169E1]", text: "text-white", glow: "glow-cyan" },
      { bg: "bg-[#0000CD]", text: "text-white", glow: "glow-purple" },
      { bg: "bg-[#00BFFF]", text: "text-[#0B0F19]", glow: "glow-cyan" },
      { bg: "bg-[#1E90FF]", text: "text-white", glow: "glow-cyan" },
      { bg: "bg-[#6495ED]", text: "text-white", glow: "glow-cyan" },
      { bg: "bg-[#5F9EA0]", text: "text-white", glow: "glow-cyan" },
      { bg: "bg-gradient-to-br from-[#E0FFFF] to-[#87CEEB]", text: "text-[#0B0F19]", glow: "glow-cyan" },
      { bg: "bg-gradient-to-br from-[#87CEEB] to-[#4169E1]", text: "text-white", glow: "glow-cyan" },
      { bg: "bg-gradient-to-br from-[#4169E1] to-[#0000CD]", text: "text-white", glow: "glow-purple" },
      { bg: "bg-gradient-to-br from-[#00BFFF] to-[#1E90FF]", text: "text-white", glow: "glow-cyan" },
      { bg: "bg-gradient-to-br from-[#B0E0E6] to-[#4682B4]", text: "text-white", glow: "glow-cyan" },
      { bg: "bg-gradient-to-br from-[#E0FFFF] via-[#4682B4] to-[#0000CD]", text: "text-white", glow: "glow-intense-cyan" },
      { bg: "bg-gradient-to-br from-[#87CEEB] via-[#4169E1] to-[#0000CD]", text: "text-white", glow: "glow-intense-purple" },
      { bg: "bg-gradient-to-br from-[#B0E0E6] via-[#1E90FF] to-[#4169E1]", text: "text-white", glow: "glow-intense-cyan" },
    ]),
  },
  {
    id: "toxic-slime",
    name: "Toxic Slime",
    description: "Radioactive glow",
    price: 750,
    preview: "☢️",
    colors: generateColorPalette([
      { bg: "bg-[#7FFF00]", text: "text-[#0B0F19]", glow: "glow-lime" },
      { bg: "bg-[#32CD32]", text: "text-[#0B0F19]", glow: "glow-lime" },
      { bg: "bg-[#00FF00]", text: "text-[#0B0F19]", glow: "glow-lime" },
      { bg: "bg-[#00FF7F]", text: "text-[#0B0F19]", glow: "glow-lime" },
      { bg: "bg-[#00FA9A]", text: "text-[#0B0F19]", glow: "glow-lime" },
      { bg: "bg-[#00CED1]", text: "text-[#0B0F19]", glow: "glow-cyan" },
      { bg: "bg-[#ADFF2F]", text: "text-[#0B0F19]", glow: "glow-lime" },
      { bg: "bg-[#9ACD32]", text: "text-[#0B0F19]", glow: "glow-lime" },
      { bg: "bg-[#76EE00]", text: "text-[#0B0F19]", glow: "glow-lime" },
      { bg: "bg-[#00FF66]", text: "text-[#0B0F19]", glow: "glow-lime" },
      { bg: "bg-[#00FFAA]", text: "text-[#0B0F19]", glow: "glow-cyan" },
      { bg: "bg-gradient-to-br from-[#7FFF00] to-[#00FF00]", text: "text-[#0B0F19]", glow: "glow-lime" },
      { bg: "bg-gradient-to-br from-[#00FF00] to-[#00FF7F]", text: "text-[#0B0F19]", glow: "glow-lime" },
      { bg: "bg-gradient-to-br from-[#00FA9A] to-[#00CED1]", text: "text-[#0B0F19]", glow: "glow-cyan" },
      { bg: "bg-gradient-to-br from-[#ADFF2F] to-[#32CD32]", text: "text-[#0B0F19]", glow: "glow-lime" },
      { bg: "bg-gradient-to-br from-[#7FFF00] via-[#00FF00] to-[#00CED1]", text: "text-[#0B0F19]", glow: "glow-intense-lime" },
      { bg: "bg-gradient-to-br from-[#32CD32] via-[#00FA9A] to-[#00CED1]", text: "text-[#0B0F19]", glow: "glow-intense-cyan" },
      { bg: "bg-gradient-to-br from-[#ADFF2F] via-[#00FF7F] to-[#00FFAA]", text: "text-[#0B0F19]", glow: "glow-intense-lime" },
    ]),
  },
  {
    id: "royal-gold",
    name: "Royal Gold",
    description: "Luxury golden shine",
    price: 1000,
    preview: "👑",
    colors: generateColorPalette([
      { bg: "bg-[#FFE4B5]", text: "text-[#0B0F19]", glow: "glow-yellow" },
      { bg: "bg-[#FFD700]", text: "text-[#0B0F19]", glow: "glow-yellow" },
      { bg: "bg-[#FFA500]", text: "text-[#0B0F19]", glow: "glow-orange" },
      { bg: "bg-[#FF8C00]", text: "text-white", glow: "glow-orange" },
      { bg: "bg-[#FF6347]", text: "text-white", glow: "glow-orange" },
      { bg: "bg-[#CD853F]", text: "text-white", glow: "glow-orange" },
      { bg: "bg-[#DAA520]", text: "text-[#0B0F19]", glow: "glow-yellow" },
      { bg: "bg-[#B8860B]", text: "text-white", glow: "glow-yellow" },
      { bg: "bg-[#FFB347]", text: "text-[#0B0F19]", glow: "glow-orange" },
      { bg: "bg-[#F4A460]", text: "text-white", glow: "glow-orange" },
      { bg: "bg-gradient-to-br from-[#FFD700] to-[#FFA500]", text: "text-[#0B0F19]", glow: "glow-yellow" },
      { bg: "bg-gradient-to-br from-[#FFA500] to-[#FF8C00]", text: "text-white", glow: "glow-orange" },
      { bg: "bg-gradient-to-br from-[#FF8C00] to-[#CD853F]", text: "text-white", glow: "glow-orange" },
      { bg: "bg-gradient-to-br from-[#FFE4B5] to-[#DAA520]", text: "text-white", glow: "glow-yellow" },
      { bg: "bg-gradient-to-br from-[#FFD700] via-[#FF8C00] to-[#CD853F]", text: "text-white", glow: "glow-intense-yellow" },
      { bg: "bg-gradient-to-br from-[#FFE4B5] via-[#FFD700] to-[#FF8C00]", text: "text-white", glow: "glow-intense-orange" },
      { bg: "bg-gradient-to-br from-[#DAA520] via-[#FFA500] to-[#F4A460]", text: "text-white", glow: "glow-intense-yellow" },
    ]),
  },
  {
    id: "bubblegum-pop",
    name: "Bubblegum Pop",
    description: "Sweet pastel candy",
    price: 800,
    preview: "🍬",
    colors: generateColorPalette([
      { bg: "bg-[#FFB6C1]", text: "text-[#0B0F19]", glow: "glow-magenta" },
      { bg: "bg-[#FFC0CB]", text: "text-[#0B0F19]", glow: "glow-magenta" },
      { bg: "bg-[#FFD1DC]", text: "text-[#0B0F19]", glow: "glow-magenta" },
      { bg: "bg-[#DDA0DD]", text: "text-[#0B0F19]", glow: "glow-purple" },
      { bg: "bg-[#EE82EE]", text: "text-white", glow: "glow-purple" },
      { bg: "bg-[#DA70D6]", text: "text-white", glow: "glow-magenta" },
      { bg: "bg-[#FF69B4]", text: "text-white", glow: "glow-magenta" },
      { bg: "bg-[#FF1493]", text: "text-white", glow: "glow-magenta" },
      { bg: "bg-[#DB7093]", text: "text-white", glow: "glow-magenta" },
      { bg: "bg-[#C71585]", text: "text-white", glow: "glow-magenta" },
      { bg: "bg-gradient-to-br from-[#FFB6C1] to-[#FFC0CB]", text: "text-[#0B0F19]", glow: "glow-magenta" },
      { bg: "bg-gradient-to-br from-[#FFC0CB] to-[#DDA0DD]", text: "text-[#0B0F19]", glow: "glow-purple" },
      { bg: "bg-gradient-to-br from-[#EE82EE] to-[#DA70D6]", text: "text-white", glow: "glow-magenta" },
      { bg: "bg-gradient-to-br from-[#FF69B4] to-[#FF1493]", text: "text-white", glow: "glow-magenta" },
      { bg: "bg-gradient-to-br from-[#FFB6C1] via-[#DDA0DD] to-[#DA70D6]", text: "text-white", glow: "glow-intense-magenta" },
      { bg: "bg-gradient-to-br from-[#FFC0CB] via-[#EE82EE] to-[#DA70D6]", text: "text-white", glow: "glow-intense-purple" },
      { bg: "bg-gradient-to-br from-[#FF69B4] via-[#FF1493] to-[#C71585]", text: "text-white", glow: "glow-intense-magenta" },
    ]),
  },
  {
    id: "deep-ocean",
    name: "Deep Ocean",
    description: "Underwater depths",
    price: 900,
    preview: "🌊",
    colors: generateColorPalette([
      { bg: "bg-[#00CED1]", text: "text-[#0B0F19]", glow: "glow-cyan" },
      { bg: "bg-[#20B2AA]", text: "text-[#0B0F19]", glow: "glow-cyan" },
      { bg: "bg-[#48D1CC]", text: "text-[#0B0F19]", glow: "glow-cyan" },
      { bg: "bg-[#008B8B]", text: "text-white", glow: "glow-cyan" },
      { bg: "bg-[#006994]", text: "text-white", glow: "glow-cyan" },
      { bg: "bg-[#003F5C]", text: "text-white", glow: "glow-purple" },
      { bg: "bg-[#40E0D0]", text: "text-[#0B0F19]", glow: "glow-cyan" },
      { bg: "bg-[#00CED1]", text: "text-[#0B0F19]", glow: "glow-cyan" },
      { bg: "bg-[#5F9EA0]", text: "text-white", glow: "glow-cyan" },
      { bg: "bg-[#2F4F4F]", text: "text-white", glow: "glow-cyan" },
      { bg: "bg-gradient-to-br from-[#00CED1] to-[#48D1CC]", text: "text-[#0B0F19]", glow: "glow-cyan" },
      { bg: "bg-gradient-to-br from-[#20B2AA] to-[#008B8B]", text: "text-white", glow: "glow-cyan" },
      { bg: "bg-gradient-to-br from-[#006994] to-[#003F5C]", text: "text-white", glow: "glow-purple" },
      { bg: "bg-gradient-to-br from-[#40E0D0] to-[#5F9EA0]", text: "text-white", glow: "glow-cyan" },
      { bg: "bg-gradient-to-br from-[#00CED1] via-[#008B8B] to-[#003F5C]", text: "text-white", glow: "glow-intense-cyan" },
      { bg: "bg-gradient-to-br from-[#48D1CC] via-[#006994] to-[#003F5C]", text: "text-white", glow: "glow-intense-purple" },
      { bg: "bg-gradient-to-br from-[#40E0D0] via-[#20B2AA] to-[#2F4F4F]", text: "text-white", glow: "glow-intense-cyan" },
    ]),
  },
  {
    id: "sunset-blaze",
    name: "Sunset Blaze",
    description: "Warm sunset colors",
    price: 850,
    preview: "🌅",
    colors: generateColorPalette([
      { bg: "bg-[#FFE4E1]", text: "text-[#0B0F19]", glow: "glow-orange" },
      { bg: "bg-[#FFA07A]", text: "text-[#0B0F19]", glow: "glow-orange" },
      { bg: "bg-[#FF7F50]", text: "text-white", glow: "glow-orange" },
      { bg: "bg-[#FF6347]", text: "text-white", glow: "glow-orange" },
      { bg: "bg-[#FF4500]", text: "text-white", glow: "glow-orange" },
      { bg: "bg-[#DC143C]", text: "text-white", glow: "glow-magenta" },
      { bg: "bg-[#FA8072]", text: "text-white", glow: "glow-orange" },
      { bg: "bg-[#E9967A]", text: "text-white", glow: "glow-orange" },
      { bg: "bg-[#F08080]", text: "text-white", glow: "glow-orange" },
      { bg: "bg-[#CD5C5C]", text: "text-white", glow: "glow-orange" },
      { bg: "bg-gradient-to-br from-[#FFE4E1] to-[#FF7F50]", text: "text-white", glow: "glow-orange" },
      { bg: "bg-gradient-to-br from-[#FF7F50] to-[#FF4500]", text: "text-white", glow: "glow-orange" },
      { bg: "bg-gradient-to-br from-[#FF4500] to-[#DC143C]", text: "text-white", glow: "glow-magenta" },
      { bg: "bg-gradient-to-br from-[#FFA07A] to-[#FA8072]", text: "text-white", glow: "glow-orange" },
      { bg: "bg-gradient-to-br from-[#FFA07A] via-[#FF6347] to-[#DC143C]", text: "text-white", glow: "glow-intense-orange" },
      { bg: "bg-gradient-to-br from-[#FF7F50] via-[#FF4500] to-[#DC143C]", text: "text-white", glow: "glow-intense-magenta" },
      { bg: "bg-gradient-to-br from-[#FA8072] via-[#F08080] to-[#CD5C5C]", text: "text-white", glow: "glow-intense-orange" },
    ]),
  },
  {
    id: "electric-purple",
    name: "Electric Purple",
    description: "Vibrant electric energy",
    price: 1200,
    preview: "⚡",
    colors: generateColorPalette([
      { bg: "bg-[#DDA0DD]", text: "text-[#0B0F19]", glow: "glow-purple" },
      { bg: "bg-[#BA55D3]", text: "text-white", glow: "glow-purple" },
      { bg: "bg-[#9370DB]", text: "text-white", glow: "glow-purple" },
      { bg: "bg-[#8B008B]", text: "text-white", glow: "glow-magenta" },
      { bg: "bg-[#9400D3]", text: "text-white", glow: "glow-purple" },
      { bg: "bg-[#8A2BE2]", text: "text-white", glow: "glow-purple" },
      { bg: "bg-[#9932CC]", text: "text-white", glow: "glow-purple" },
      { bg: "bg-[#800080]", text: "text-white", glow: "glow-purple" },
      { bg: "bg-[#663399]", text: "text-white", glow: "glow-purple" },
      { bg: "bg-[#6A0DAD]", text: "text-white", glow: "glow-purple" },
      { bg: "bg-gradient-to-br from-[#DDA0DD] to-[#9370DB]", text: "text-white", glow: "glow-purple" },
      { bg: "bg-gradient-to-br from-[#BA55D3] to-[#8B008B]", text: "text-white", glow: "glow-magenta" },
      { bg: "bg-gradient-to-br from-[#9400D3] to-[#8A2BE2]", text: "text-white", glow: "glow-purple" },
      { bg: "bg-gradient-to-br from-[#9932CC] to-[#800080]", text: "text-white", glow: "glow-purple" },
      { bg: "bg-gradient-to-br from-[#DDA0DD] via-[#8B008B] to-[#8A2BE2]", text: "text-white", glow: "glow-intense-purple" },
      { bg: "bg-gradient-to-br from-[#BA55D3] via-[#9400D3] to-[#8A2BE2]", text: "text-white", glow: "glow-intense-magenta" },
      { bg: "bg-gradient-to-br from-[#9932CC] via-[#800080] to-[#6A0DAD]", text: "text-white", glow: "glow-intense-purple" },
    ]),
  },
  {
    id: "matrix-code",
    name: "Matrix Code",
    description: "Digital green matrix",
    price: 1500,
    preview: "💻",
    colors: generateColorPalette([
      { bg: "bg-[#00FF00]", text: "text-[#0B0F19]", glow: "glow-lime" },
      { bg: "bg-[#00DD00]", text: "text-[#0B0F19]", glow: "glow-lime" },
      { bg: "bg-[#00BB00]", text: "text-white", glow: "glow-lime" },
      { bg: "bg-[#009900]", text: "text-white", glow: "glow-lime" },
      { bg: "bg-[#007700]", text: "text-white", glow: "glow-lime" },
      { bg: "bg-[#005500]", text: "text-white", glow: "glow-lime" },
      { bg: "bg-[#00EE00]", text: "text-[#0B0F19]", glow: "glow-lime" },
      { bg: "bg-[#00CC00]", text: "text-white", glow: "glow-lime" },
      { bg: "bg-[#00AA00]", text: "text-white", glow: "glow-lime" },
      { bg: "bg-[#008800]", text: "text-white", glow: "glow-lime" },
      { bg: "bg-gradient-to-br from-[#00FF00] to-[#00BB00]", text: "text-[#0B0F19]", glow: "glow-lime" },
      { bg: "bg-gradient-to-br from-[#00DD00] to-[#009900]", text: "text-white", glow: "glow-lime" },
      { bg: "bg-gradient-to-br from-[#009900] to-[#005500]", text: "text-white", glow: "glow-lime" },
      { bg: "bg-gradient-to-br from-[#00EE00] to-[#00AA00]", text: "text-white", glow: "glow-lime" },
      { bg: "bg-gradient-to-br from-[#00FF00] via-[#009900] to-[#005500]", text: "text-white", glow: "glow-intense-lime" },
      { bg: "bg-gradient-to-br from-[#00DD00] via-[#007700] to-[#005500]", text: "text-white", glow: "glow-intense-lime" },
      { bg: "bg-gradient-to-br from-[#00EE00] via-[#00AA00] to-[#006600]", text: "text-white", glow: "glow-intense-lime" },
    ]),
  },
  {
    id: "cosmic-space",
    name: "Cosmic Space",
    description: "Stellar galaxy colors",
    price: 2000,
    preview: "🌌",
    colors: generateColorPalette([
      { bg: "bg-[#191970]", text: "text-white", glow: "glow-purple" },
      { bg: "bg-[#4B0082]", text: "text-white", glow: "glow-purple" },
      { bg: "bg-[#483D8B]", text: "text-white", glow: "glow-purple" },
      { bg: "bg-[#6A5ACD]", text: "text-white", glow: "glow-purple" },
      { bg: "bg-[#7B68EE]", text: "text-white", glow: "glow-purple" },
      { bg: "bg-[#9370DB]", text: "text-white", glow: "glow-purple" },
      { bg: "bg-[#000080]", text: "text-white", glow: "glow-purple" },
      { bg: "bg-[#0000CD]", text: "text-white", glow: "glow-purple" },
      { bg: "bg-[#00008B]", text: "text-white", glow: "glow-purple" },
      { bg: "bg-[#4169E1]", text: "text-white", glow: "glow-purple" },
      { bg: "bg-gradient-to-br from-[#191970] to-[#4B0082]", text: "text-white", glow: "glow-purple" },
      { bg: "bg-gradient-to-br from-[#483D8B] to-[#6A5ACD]", text: "text-white", glow: "glow-purple" },
      { bg: "bg-gradient-to-br from-[#7B68EE] to-[#9370DB]", text: "text-white", glow: "glow-purple" },
      { bg: "bg-gradient-to-br from-[#000080] to-[#0000CD]", text: "text-white", glow: "glow-purple" },
      { bg: "bg-gradient-to-br from-[#191970] via-[#6A5ACD] to-[#9370DB]", text: "text-white", glow: "glow-intense-purple" },
      { bg: "bg-gradient-to-br from-[#4B0082] via-[#7B68EE] to-[#9370DB]", text: "text-white", glow: "glow-intense-magenta" },
      { bg: "bg-gradient-to-br from-[#000080] via-[#4169E1] to-[#6A5ACD]", text: "text-white", glow: "glow-intense-purple" },
    ]),
  },
  {
    id: "ruby-blood",
    name: "Ruby Blood",
    description: "Deep crimson red",
    price: 1800,
    preview: "💎",
    colors: generateColorPalette([
      { bg: "bg-[#FF6B6B]", text: "text-white", glow: "glow-orange" },
      { bg: "bg-[#EE5A6F]", text: "text-white", glow: "glow-orange" },
      { bg: "bg-[#C92A2A]", text: "text-white", glow: "glow-orange" },
      { bg: "bg-[#A61E1E]", text: "text-white", glow: "glow-magenta" },
      { bg: "bg-[#8B0000]", text: "text-white", glow: "glow-magenta" },
      { bg: "bg-[#660000]", text: "text-white", glow: "glow-magenta" },
      { bg: "bg-[#DC143C]", text: "text-white", glow: "glow-orange" },
      { bg: "bg-[#B22222]", text: "text-white", glow: "glow-orange" },
      { bg: "bg-[#8B0000]", text: "text-white", glow: "glow-magenta" },
      { bg: "bg-[#800000]", text: "text-white", glow: "glow-magenta" },
      { bg: "bg-gradient-to-br from-[#FF6B6B] to-[#C92A2A]", text: "text-white", glow: "glow-orange" },
      { bg: "bg-gradient-to-br from-[#EE5A6F] to-[#A61E1E]", text: "text-white", glow: "glow-magenta" },
      { bg: "bg-gradient-to-br from-[#8B0000] to-[#660000]", text: "text-white", glow: "glow-magenta" },
      { bg: "bg-gradient-to-br from-[#DC143C] to-[#B22222]", text: "text-white", glow: "glow-orange" },
      { bg: "bg-gradient-to-br from-[#FF6B6B] via-[#A61E1E] to-[#660000]", text: "text-white", glow: "glow-intense-orange" },
      { bg: "bg-gradient-to-br from-[#C92A2A] via-[#8B0000] to-[#660000]", text: "text-white", glow: "glow-intense-magenta" },
      { bg: "bg-gradient-to-br from-[#DC143C] via-[#B22222] to-[#800000]", text: "text-white", glow: "glow-intense-orange" },
    ]),
  },
];

// Game Background Data
export interface GameBackground {
  id: string;
  name: string;
  description: string;
  price: number;
  preview: string;
  bgClass: string;
  boardBg: string;
  glowColor: string;
}

export const availableBackgrounds: GameBackground[] = [
  {
    id: "default-dark",
    name: "Dark Void",
    description: "Classic dark background",
    price: 0,
    preview: "🌑",
    bgClass: "bg-gradient-to-br from-[#0B0F19] to-[#1A1A1A]",
    boardBg: "bg-[#1A1A1A]/80",
    glowColor: "#00FFFF",
  },
  {
    id: "cyber-grid",
    name: "Cyber Grid",
    description: "Futuristic grid pattern",
    price: 600,
    preview: "🔲",
    bgClass: "bg-gradient-to-br from-[#0D1117] to-[#161B22]",
    boardBg: "bg-[#0D1117]/90",
    glowColor: "#00FFFF",
  },
  {
    id: "neon-city",
    name: "Neon City",
    description: "Urban neon lights",
    price: 800,
    preview: "🌃",
    bgClass: "bg-gradient-to-br from-[#1A0A2E] to-[#0F0326]",
    boardBg: "bg-[#16213E]/80",
    glowColor: "#FF00FF",
  },
  {
    id: "purple-haze",
    name: "Purple Haze",
    description: "Mystic purple fog",
    price: 700,
    preview: "🔮",
    bgClass: "bg-gradient-to-br from-[#2D1B69] to-[#1A0F3D]",
    boardBg: "bg-[#1A0F3D]/80",
    glowColor: "#A100FF",
  },
  {
    id: "fire-storm",
    name: "Fire Storm",
    description: "Blazing inferno",
    price: 900,
    preview: "🔥",
    bgClass: "bg-gradient-to-br from-[#330000] to-[#1A0000]",
    boardBg: "bg-[#2D0000]/80",
    glowColor: "#FF6A00",
  },
  {
    id: "ocean-depths",
    name: "Ocean Depths",
    description: "Deep underwater",
    price: 850,
    preview: "🌊",
    bgClass: "bg-gradient-to-br from-[#001F3F] to-[#001429]",
    boardBg: "bg-[#002B45]/80",
    glowColor: "#00CED1",
  },
  {
    id: "toxic-waste",
    name: "Toxic Waste",
    description: "Radioactive zone",
    price: 1000,
    preview: "☢️",
    bgClass: "bg-gradient-to-br from-[#0A2F0A] to-[#051F05]",
    boardBg: "bg-[#0D3D0D]/80",
    glowColor: "#00FF00",
  },
  {
    id: "galaxy-stars",
    name: "Galaxy Stars",
    description: "Starry cosmos",
    price: 1200,
    preview: "✨",
    bgClass: "bg-gradient-to-br from-[#0A0E27] to-[#16003B]",
    boardBg: "bg-[#1A0F3D]/80",
    glowColor: "#9370DB",
  },
  {
    id: "sunset-sky",
    name: "Sunset Sky",
    description: "Warm evening glow",
    price: 750,
    preview: "🌅",
    bgClass: "bg-gradient-to-br from-[#2C1810] to-[#1A0F08]",
    boardBg: "bg-[#3D2415]/80",
    glowColor: "#FF7F50",
  },
  {
    id: "arctic-ice",
    name: "Arctic Ice",
    description: "Frozen wasteland",
    price: 800,
    preview: "🧊",
    bgClass: "bg-gradient-to-br from-[#0A1929] to-[#051219]",
    boardBg: "bg-[#0D2840]/80",
    glowColor: "#87CEEB",
  },
  {
    id: "cherry-blossom",
    name: "Cherry Blossom",
    description: "Soft pink petals",
    price: 950,
    preview: "🌸",
    bgClass: "bg-gradient-to-br from-[#2D1A28] to-[#1A0F18]",
    boardBg: "bg-[#3D2535]/80",
    glowColor: "#FFB6C1",
  },
  {
    id: "emerald-forest",
    name: "Emerald Forest",
    description: "Lush green nature",
    price: 850,
    preview: "🌲",
    bgClass: "bg-gradient-to-br from-[#0F2A1A] to-[#081A0F]",
    boardBg: "bg-[#143D25]/80",
    glowColor: "#32CD32",
  },
];
